#pragma once

#include "GameBindings.h"

namespace mcoverlay {

// Resolver-owned until publication. Every field is immutable after
// m_resolutionPhase is release-stored as Resolved. The render thread performs
// an acquire load before dereferencing m_cache, so it can never observe a
// partially initialized JNI cache.
struct GameBindings::BindingCache final {
    jclass minecraftClass = nullptr;
    jclass playerClass = nullptr;
    jclass livingClass = nullptr;
    jclass hostileClass = nullptr;
    jclass entityClass = nullptr;
    jclass fireballClass = nullptr;
    jclass aabbClass = nullptr;
    jclass worldClass = nullptr;
    jclass worldClientClass = nullptr;
    jclass stateClass = nullptr;
    jclass blockClass = nullptr;
    jclass blockPosClass = nullptr;
    jclass bedClass = nullptr;
    jclass chunkProviderClass = nullptr;
    jclass chunkClass = nullptr;
    jclass storageClass = nullptr;
    jclass activeRenderInfoClass = nullptr;
    jclass renderManagerClass = nullptr;
    jclass timerClass = nullptr;
    jclass gameSettingsClass = nullptr;
    jclass entityRendererClass = nullptr;
    jclass renderGlobalClass = nullptr;
    jclass keyBindingClass = nullptr;
    jclass playerControllerClass = nullptr;
    jclass serverDataClass = nullptr;
    jclass itemBlockClass = nullptr;
    jclass enumFacingClass = nullptr;
    jclass vec3Class = nullptr;
    jclass rayVectorClass = nullptr;
    jclass rayHitClass = nullptr;
    jclass networkPacketClass = nullptr;
    jclass movementPacketClass = nullptr;
    jclass positionPacketClass = nullptr;
    jclass lookPacketClass = nullptr;
    jclass positionLookPacketClass = nullptr;
    jclass packetNetHandlerClass = nullptr;
    jmethodID rayVectorConstructor = nullptr;
    jmethodID clickMouse = nullptr;
    jmethodID rightClickMouse = nullptr;
    jmethodID knockBack = nullptr;
    jmethodID handleEntityVelocity=nullptr;
    jmethodID velocityEntityId=nullptr;
    jmethodID sendClickBlock = nullptr;
    jmethodID moveFlying = nullptr;
    jmethodID moveEntityWithHeading = nullptr;
    jmethodID getAIMoveSpeed = nullptr;
    jmethodID isSprinting = nullptr;
    jmethodID setSprinting = nullptr;
    jmethodID swingItem = nullptr;
    jmethodID rayTraceBlocks = nullptr;
    jmethodID getEntityById = nullptr;
    jmethodID getItemUseDuration = nullptr;
    jmethodID isUsingItem = nullptr;
    jmethodID getEyeHeight = nullptr;
    jfieldID hitVector = nullptr;
    jfieldID rayBlockPos = nullptr;
    jfieldID raySideHit = nullptr;
    jfieldID cameraMouseOver = nullptr; // read-only, never a redirected target
    jfieldID cameraHitEntity = nullptr;
    jfieldID cameraHitType = nullptr;
    jfieldID entityTicks = nullptr;
    jmethodID isSneaking = nullptr;
    jclass diggingPacketClass = nullptr;
    jmethodID diggingPosition = nullptr, diggingAction = nullptr, enumOrdinal = nullptr;
    std::array<jmethodID, 3U> blockPosCoordinates{};
    jmethodID facingIndex = nullptr;
    jmethodID addToSendQueue = nullptr;
    jmethodID movementPacketConstructor = nullptr;
    jmethodID positionPacketConstructor = nullptr;
    jmethodID lookPacketConstructor = nullptr;
    jmethodID positionLookPacketConstructor = nullptr;
    std::array<jfieldID, 3U> packetPosition{};
    jfieldID packetYaw = nullptr;
    jfieldID packetPitch = nullptr;
    jfieldID packetOnGround = nullptr;
    std::array<jfieldID, 3U> vectorFields{};
    jclass chatComponentClass = nullptr;
    jclass chatTextClass = nullptr;
    jclass chatSerializerClass = nullptr;
    jobject renderManagerObject = nullptr;
    jobject timerObject = nullptr;
    jobject modelViewBuffer = nullptr;
    jobject projectionBuffer = nullptr;
    jobject viewportBuffer = nullptr;

    jmethodID getMinecraft = nullptr;
    jfieldID minecraftInstanceField = nullptr;
    jfieldID playerField = nullptr;
    jmethodID getHealth = nullptr;
    jfieldID hurtTime = nullptr;
    jmethodID getMaxHealth = nullptr;
    jmethodID getEntityId = nullptr;
    jmethodID getBounds = nullptr;
    jmethodID isMainThread = nullptr;
    jmethodID isSingleplayer = nullptr;
    jfieldID worldField = nullptr;
    jfieldID positionX = nullptr;
    jfieldID positionY = nullptr;
    jfieldID positionZ = nullptr;
    std::array<jfieldID, 3U> previousPosition{};
    jmethodID getLoadedEntities = nullptr;
    jfieldID loadedEntitiesField = nullptr;
    jfieldID playerEntities = nullptr;
    jmethodID getName = nullptr;
    jmethodID isInvisible = nullptr;
    jmethodID getDisplayName = nullptr;
    jmethodID getFormattedText = nullptr;
    jmethodID chatTextConstructor = nullptr;
    jmethodID addChatMessage = nullptr;
    jmethodID parseChatJson = nullptr;
    jmethodID listSize = nullptr;
    jmethodID listGet = nullptr;
    jmethodID blockPosConstructor = nullptr;
    jmethodID getBlockState = nullptr;
    jmethodID getBlock = nullptr;
    jmethodID getBlockMetadata = nullptr;
    jmethodID setIngameFocus = nullptr;
    jmethodID setIngameNotInFocus = nullptr;
    jmethodID getChunkProvider = nullptr;
    jfieldID chunkListingField = nullptr;
    jfieldID chunkX = nullptr;
    jfieldID chunkZ = nullptr;
    jmethodID getStorageArrays = nullptr;
    jmethodID getStorageData = nullptr;
    jmethodID listToArray = nullptr;
    jmethodID collectionToArray = nullptr;
    jmethodID getRenderManager = nullptr;
    std::array<jfieldID, 3U> renderPosition{};
    jfieldID activeModelView = nullptr;
    jfieldID activeProjection = nullptr;
    jfieldID activeViewport = nullptr;
    jfieldID timerField = nullptr;
    jfieldID renderPartialTicks = nullptr;
    jfieldID gameSettingsField = nullptr;
    jfieldID thirdPersonView = nullptr;
    jmethodID updateCameraAndRender = nullptr;
    jmethodID orientCamera = nullptr;
    jmethodID setAngles = nullptr;
    jmethodID setupTerrain = nullptr;
    jfieldID currentScreen = nullptr;
    jmethodID aabbConstructor = nullptr;
    jmethodID getCollidingBoxes = nullptr;
    jfieldID keyBindSneakField = nullptr;
    jfieldID keyBindSprintField = nullptr;
    jfieldID keyBindsHotbar = nullptr;
    jmethodID keyBindingIsPressed = nullptr;
    jmethodID syncCurrentPlayItem = nullptr;
    std::array<jfieldID, 5U> movementKeyFields{};
    jmethodID getKeyCode = nullptr;
    jmethodID setKeyBindState = nullptr;
    jfieldID mouseSensitivity = nullptr;
    jfieldID rotationYaw = nullptr;
    jfieldID rotationPitch = nullptr;
    jfieldID previousRotationYaw = nullptr;
    jfieldID previousRotationPitch = nullptr;
    std::array<jfieldID, 2U> movementInputFields{};
    std::array<jfieldID, 3U> motionFields{};
    jfieldID onGround = nullptr;
    jmethodID jump = nullptr;
    jmethodID isAirBlock = nullptr;
    jmethodID getCurrentServerData = nullptr;
    jfieldID serverIp = nullptr;
    jfieldID playerControllerField = nullptr;
    jfieldID currentItem = nullptr;
    jfieldID mainInventory = nullptr;
    jmethodID getBlockFromItem = nullptr;
    jmethodID getIdFromBlock = nullptr;
    jmethodID getFacingByIndex = nullptr;
    jmethodID onPlayerRightClick = nullptr;
    jmethodID clickBlock = nullptr;
    jmethodID onPlayerDamageBlock = nullptr;
    jmethodID resetBlockRemoving = nullptr;
    jmethodID getBlockReachDistance = nullptr;
    jmethodID getStrVsBlock = nullptr;
    jmethodID attackEntity = nullptr;
    jmethodID windowClick = nullptr;
    jmethodID vec3Constructor = nullptr;
    jfieldID minX = nullptr;
    jfieldID minY = nullptr;
    jfieldID minZ = nullptr;
    jfieldID maxX = nullptr;
    jfieldID maxY = nullptr;
    jfieldID maxZ = nullptr;

    jclass scoreboardClass = nullptr;
    jclass scoreObjectiveClass = nullptr;
    jclass scoreClass = nullptr;
    jclass scorePlayerTeamClass = nullptr;
    jclass netHandlerClass = nullptr;
    jclass networkPlayerInfoClass = nullptr;
    jclass gameProfileClass = nullptr;
    jclass itemStackClass = nullptr;
    jclass itemClass = nullptr;
    jclass itemArmorClass = nullptr;
    jclass itemSwordClass = nullptr;
    jclass inventoryPlayerClass = nullptr;
    jclass enchantmentHelperClass = nullptr;
    jclass abstractClientPlayerClass = nullptr;
    jclass resourceLocationClass = nullptr;
    jclass textureManagerClass = nullptr;
    jclass textureObjectClass = nullptr;
    jclass uuidClass = nullptr;

    jmethodID getScoreboard = nullptr;
    jmethodID getObjectiveInDisplaySlot = nullptr;
    jmethodID getPlayersTeam = nullptr;
    jmethodID getSortedScores = nullptr;
    jmethodID getPlayerName = nullptr;
    jmethodID formatPlayerName = nullptr;
    jmethodID getNetHandler = nullptr;
    jmethodID getPlayerInfoMap = nullptr;
    jmethodID getGameProfile = nullptr;
    jmethodID gameProfileGetName = nullptr;
    jmethodID gameProfileGetId = nullptr;
    jmethodID uuidToString = nullptr;
    jfieldID inventoryField = nullptr;
    jfieldID armorInventoryField = nullptr;
    jmethodID getItem = nullptr;
    jmethodID hasColor = nullptr;
    jmethodID getColor = nullptr;
    jmethodID getEnchantmentLevel = nullptr;
    jmethodID getEquipmentInSlot = nullptr;
    jmethodID getIdFromItem = nullptr;
    jfieldID stackSize = nullptr;
    jmethodID getItemDamage = nullptr;
    jmethodID getUniqueId = nullptr;
    jmethodID getLocationSkin = nullptr;
    jmethodID getTextureManager = nullptr;
    jmethodID getTexture = nullptr;
    jmethodID getGlTextureId = nullptr;

    const MappingProfile* profile = nullptr;
};

} // namespace mcoverlay
